"""initial schema

Revision ID: ba3c23a19ce9
Revises: 0001_initial_schema
Create Date: 2026-09-14 08:42:20.875623

Autogenerated (`alembic revision --autogenerate`) against every model in
`app/db/models/` (ARCH-008), then hand-extended per the Phase-1 placeholder
migration's own instructions with the two things autogenerate cannot produce:

- **Row-level security** (ARCH-034) on `records.patient`, `records.patient_record`,
  and `memory.patient_context`, keyed on the `app.current_patient_scope` session
  GUC (set by `app.db.session.session_scope(patient_scope=...)`). A policy
  applies to every role except the table owner (superuser/migration role), so
  it constrains the restricted runtime `hrag_app` role, never Alembic itself.
  **Fail-open when the GUC is unset or empty** — service/ingestion paths that
  never call `session_scope(patient_scope=...)` (everything built so far:
  `ingest_records`, `process_document`) see every row, matching how they're
  actually used today; only a future per-conversation query path (Phase 3/4,
  one patient per session — PRD-NG-011) that *does* set the GUC gets narrowed
  to that one patient. See DEVIATIONS.md #63.
- **The audit append-only trigger** (ARCH-035): a `BEFORE UPDATE OR DELETE`
  trigger on `audit.audit_event` that raises unconditionally, regardless of
  role — defense in depth *beyond* the role GRANTs
  (`deploy/postgres/init/01_schemas_roles.sql` already revokes UPDATE/DELETE
  from `hrag_app`, but a trigger also stops the table owner / a future role
  that's ever mistakenly granted those privileges; triggers, unlike RLS
  policies, are not bypassed for the owner).
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ba3c23a19ce9'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None

_PATIENT_SCOPED_TABLES = (
    ("records", "patient", "id"),
    ("records", "patient_record", "patient_id"),
    ("memory", "patient_context", "patient_id"),
)

_PATIENT_SCOPE_POLICY_USING = """
    current_setting('app.current_patient_scope', true) IS NULL
    OR current_setting('app.current_patient_scope', true) = ''
    OR {column}::text = current_setting('app.current_patient_scope', true)
"""

_AUDIT_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION audit.reject_update_delete() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit.audit_event is append-only; % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('query_text_enc', sa.LargeBinary(), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('response_text_enc', sa.LargeBinary(), nullable=True),
    sa.Column('grounding_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event')),
    schema='audit'
    )
    op.create_table('corpus_snapshot',
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('embedding_collection', sa.String(length=128), nullable=False),
    sa.Column('document_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_snapshot')),
    schema='corpus'
    )
    op.create_table('document',
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('licence', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    schema='corpus'
    )
    op.create_table('eval_question',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('expected_outcome', sa.String(length=24), nullable=True),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('target_guideline_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gold_relevant_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gold_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generator_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_fixed_testset', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_question')),
    schema='eval'
    )
    op.create_table('eval_run',
    sa.Column('snapshot_label', sa.String(length=64), nullable=False),
    sa.Column('corpus_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_run')),
    schema='eval'
    )
    op.create_table('irr_batch',
    sa.Column('slice_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('per_domain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secondary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('n_raters', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_irr_batch')),
    schema='eval'
    )
    op.create_table('rubric_domain',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('anchor_1', sa.Text(), nullable=False),
    sa.Column('anchor_2', sa.Text(), nullable=False),
    sa.Column('anchor_3', sa.Text(), nullable=False),
    sa.Column('anchor_4', sa.Text(), nullable=False),
    sa.Column('anchor_5', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_rubric_domain')),
    schema='eval'
    )
    op.create_table('escalation',
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_code', sa.String(length=48), nullable=False),
    sa.Column('trigger_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_answer_enc', sa.LargeBinary(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation')),
    schema='hitl'
    )
    op.create_table('role',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_role')),
    schema='iam'
    )
    op.create_table('service_account',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_account')),
    sa.UniqueConstraint('name', name=op.f('uq_service_account_name')),
    schema='iam'
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_clinician', sa.Boolean(), nullable=False),
    sa.Column('identity_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    schema='iam'
    )
    op.create_table('conversation',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    schema='memory'
    )
    op.create_table('patient_context',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_context')),
    schema='memory'
    )
    op.create_table('patient',
    sa.Column('mrn_enc', sa.LargeBinary(), nullable=False),
    sa.Column('mrn_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('data_class', sa.String(length=16), nullable=False),
    sa.Column('consent_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient')),
    schema='records'
    )
    op.create_index(op.f('ix_records_patient_mrn_hash'), 'patient', ['mrn_hash'], unique=True, schema='records')
    op.create_table('record_field_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('field_path', sa.String(length=256), nullable=False),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_field_policy')),
    schema='records'
    )
    op.create_table('document_version',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('format_profile', sa.String(length=24), nullable=True),
    sa.Column('parse_quality', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['corpus.document.id'], name=op.f('fk_document_version_document_id_document')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['corpus.document_version.id'], name=op.f('fk_document_version_supersedes_id_document_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version')),
    schema='corpus'
    )
    op.create_table('result',
    sa.Column('eval_question_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('expected_outcome', sa.String(length=24), nullable=True),
    sa.Column('observed_outcome', sa.String(length=16), nullable=True),
    sa.Column('answer_enc', sa.LargeBinary(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('queue_state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_question_id'], ['eval.eval_question.id'], name=op.f('fk_result_eval_question_id_eval_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result')),
    schema='eval'
    )
    op.create_table('hitl_decision',
    sa.Column('escalation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('edited_answer_enc', sa.LargeBinary(), nullable=True),
    sa.Column('span_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_context_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escalation_id'], ['hitl.escalation.id'], name=op.f('fk_hitl_decision_escalation_id_escalation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hitl_decision')),
    schema='hitl'
    )
    op.create_table('session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam.user.id'], name=op.f('fk_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    schema='iam'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['iam.role.code'], name=op.f('fk_user_role_role_code_role')),
    sa.ForeignKeyConstraint(['user_id'], ['iam.user.id'], name=op.f('fk_user_role_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_code', name=op.f('pk_user_role')),
    schema='iam'
    )
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content_enc', sa.LargeBinary(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hitl_ref', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['memory.conversation.id'], name=op.f('fk_message_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    schema='memory'
    )
    op.create_table('patient_record',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_enc', sa.LargeBinary(), nullable=False),
    sa.Column('field_index', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('source_batch_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['records.patient.id'], name=op.f('fk_patient_record_patient_id_patient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_record')),
    schema='records'
    )
    op.create_table('chunk',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('section_number', sa.String(length=32), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('figure_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['corpus.document_version.id'], name=op.f('fk_chunk_document_version_id_document_version')),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['corpus.chunk.id'], name=op.f('fk_chunk_parent_chunk_id_chunk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk')),
    schema='corpus'
    )
    op.create_table('irr_score',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('domain_code', sa.String(length=48), nullable=True),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('n_raters', sa.Integer(), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['eval.result.id'], name=op.f('fk_irr_score_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_irr_score')),
    schema='eval'
    )
    op.create_table('rating_round',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('is_original_rater', sa.Boolean(), nullable=False),
    sa.Column('accept_action_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['eval.result.id'], name=op.f('fk_rating_round_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating_round')),
    sa.UniqueConstraint('result_id', 'rater_id', name='distinct_rater_per_result'),
    schema='eval'
    )
    op.create_table('result_archive',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('irr_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['eval.result.id'], name=op.f('fk_result_archive_result_id_result')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_result_archive')),
    schema='eval'
    )
    op.create_table('rubric_rating',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('domain_code', sa.String(length=48), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_round_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_code'], ['eval.rubric_domain.code'], name=op.f('fk_rubric_rating_domain_code_rubric_domain')),
    sa.ForeignKeyConstraint(['rating_round_id'], ['eval.rating_round.id'], name=op.f('fk_rubric_rating_rating_round_id_rating_round')),
    sa.ForeignKeyConstraint(['result_id'], ['eval.result.id'], name=op.f('fk_rubric_rating_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_rating')),
    sa.UniqueConstraint('result_id', 'rater_id', 'domain_code', name='one_score_per_domain_per_rater'),
    schema='eval'
    )
    # ### end Alembic commands ###

    # --- Row-level security (ARCH-034; DEVIATIONS.md #63) ---
    for schema, table, column in _PATIENT_SCOPED_TABLES:
        using_clause = _PATIENT_SCOPE_POLICY_USING.format(column=column)
        op.execute(f"ALTER TABLE {schema}.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY patient_scope ON {schema}.{table} USING ({using_clause})"
        )

    # --- Audit append-only trigger, beyond the role GRANTs (ARCH-035) ---
    op.execute(_AUDIT_TRIGGER_FUNCTION)
    op.execute(
        "CREATE TRIGGER audit_event_no_update_delete "
        "BEFORE UPDATE OR DELETE ON audit.audit_event "
        "FOR EACH ROW EXECUTE FUNCTION audit.reject_update_delete()"
    )


def downgrade() -> None:
    # --- reverse the audit trigger + RLS policies before dropping tables ---
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_update_delete ON audit.audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit.reject_update_delete()")
    for schema, table, _column in _PATIENT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS patient_scope ON {schema}.{table}")
        op.execute(f"ALTER TABLE {schema}.{table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rubric_rating', schema='eval')
    op.drop_table('result_archive', schema='eval')
    op.drop_table('rating_round', schema='eval')
    op.drop_table('irr_score', schema='eval')
    op.drop_table('chunk', schema='corpus')
    op.drop_table('patient_record', schema='records')
    op.drop_table('message', schema='memory')
    op.drop_table('user_role', schema='iam')
    op.drop_table('session', schema='iam')
    op.drop_table('hitl_decision', schema='hitl')
    op.drop_table('result', schema='eval')
    op.drop_table('document_version', schema='corpus')
    op.drop_table('record_field_policy', schema='records')
    op.drop_index(op.f('ix_records_patient_mrn_hash'), table_name='patient', schema='records')
    op.drop_table('patient', schema='records')
    op.drop_table('patient_context', schema='memory')
    op.drop_table('conversation', schema='memory')
    op.drop_table('user', schema='iam')
    op.drop_table('service_account', schema='iam')
    op.drop_table('role', schema='iam')
    op.drop_table('escalation', schema='hitl')
    op.drop_table('rubric_domain', schema='eval')
    op.drop_table('irr_batch', schema='eval')
    op.drop_table('eval_run', schema='eval')
    op.drop_table('eval_question', schema='eval')
    op.drop_table('document', schema='corpus')
    op.drop_table('corpus_snapshot', schema='corpus')
    op.drop_table('audit_event', schema='audit')
    # ### end Alembic commands ###
